### ISSUE TITLE
Missing ES5 cjs build

### ISSUE THREAD

**Issue by NicoZelaya** [haadcode/logplease#6]
Hi! First of all, thank you for this great library!

We are using your library on a package of our own, and we have customers that download our library from NPM with yours as a dep. 
Thing is that some people have applications that doesn't always run on environments with ES6 support. As your main file contains ES6 code, the require of logplease is causing issues to them.

Would you mind if I submit a PR adding a build with the transpiling? I can also update the webpack configs to work with Webpack 2 in the process (and of course, I'll update the docs).

This is a great library and we don't want to move away just for this tiny issue.

Thanks in advance!

**Comment by NicoZelaya** [comment]
Ping

**Comment by NicoZelaya** [comment]
@haadcode Sorry for bothering, could you let me know what you think?

**Comment by haadcode** [comment]
Sorry @NicoZelaya this completely fell through the cracks and I just re-discovered this issue. This sounds great and would be happy to accept a PR and work with you to get it merged. If you still want to, that is.

**Comment by haadcode** [comment]
@NicoZelaya this got [PR'd](https://github.com/haadcode/logplease/pull/7) by @alexbadm and has been merged. I just published v1.2.14 to npm and you'll find the ES5 build in `./es5/index.js`.

Let me know if you're missing something and this doesn't solve it for you, want to make sure you can use it. I'm gonna go ahead and close this issue assuming this fixes it for you, but if not, please do re-open the issue.

Thanks once more @alexbadm for implementing this!

**Comment by NicoZelaya** [comment]
That's great news! I'm working on something right now but I'll let you know if there's anything else after I can test the new version. Either way the change looks good so good hopes on this!

Thank you both @alexbadm and @haadcode !
